### ISSUE TITLE
calculate FPL percentage if user passes annual/monthly income

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/fplapi#1]

**Comment by apranav19** [comment]
Hi, 
So the annual/monthly income will be an additional query parameter? 
Therefore, `FPL % = (income) / the calculated rate`?

**Comment by apranav19** [comment]
Also with regards to the API structure .. would we want to specify the users to specify the income and the type of income. Something like this:
`api?year=2012&size=3&income=5000&income_type=annual`?

**Comment by mapsam** [comment]
Seems good to me! Would defaulting to `month`/`annual` be helpful or does that seem unnecessary?

**Comment by apranav19** [comment]
Since our data returns the `amount` at an annual rate, we could default to annual. If the users do provide a monthly income, we would just compute the annual income. What do you think?

And also, did you guys use Python 2.x for your project?

**Comment by mapsam** [comment]
Good thinking.

> 2.x?

Currently running `2.7.6`!

**Comment by mapsam** [comment]
Resolved in #8

**Comment by mapsam** [comment]
Resolved in #8
